# image_size
size: [224, 224]

# color pixels of dermoscopy image
num_pixels: 1024

# batch size
batch_size: 8

# parameters of momentumSGD
SGD:
  lr: 0.001
  momentum: 0.9

# number of epochs
num_epochs: 2
